const String html = """
<div>
    <div style="clear:both;">
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;'><strong><em><span style="font-size:19px;">&nbsp;</span></em></strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:center;'><strong><span style="font-size:19px;">ПОЛОЖЕНИЕ&nbsp;</span></strong><strong><span style="font-size:19px;">III</span></strong><strong><span style="font-size:19px;">&nbsp;МЕЖДУНАРОДНОЙ НАУЧНО-ИССЛЕДОВАТЕЛЬСКОЙ &nbsp;ВЫСТАВКИ-КОНКУРСА &nbsp;</span></strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:center;'><strong><span style="font-size:19px;">ИСКУССТВО И НАУКА: КОСМОС</span></strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:center;'><strong><span style="font-size:19px;">&nbsp;</span></strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:center;'><span style="font-size:19px;">Синтез искусства и науки. Заявки принимаются на&nbsp;</span><a href="http://science-art.pro/#/"><span style="font-size:19px;">http://science-art.pro/#/</span></a></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong><span style="font-size:19px;">&nbsp;</span></strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Организаторы&nbsp;</strong>ФГБОУ &nbsp;ВО &laquo;Кубанский государственный университет&raquo;:</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'>Кафедра ДПИ и дизайна художественно-графического факультета; &nbsp;</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'>Кафедра анализа данных и искусственного интеллекта факультета компьютерных технологий и прикладной математики; &nbsp; &nbsp; &nbsp; &nbsp;</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'>Кафедра истории и правового регулирования массовых коммуникаций факультета журналистики; &nbsp;&nbsp;</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'>Детская школа искусств имени В.А.Филиппова.</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Генеральный партнёр выставки-конкурса:&nbsp;</strong>ARTEЛЬ&nbsp;DIGITAL</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Выставочная экспозиция будет транслироваться на интерактивном мультимедийном оборудовании &nbsp;компании&nbsp;</strong><strong>ARTEЛЬ&nbsp;</strong><strong>DIGITAL</strong><strong>&nbsp;&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>&nbsp; &nbsp;&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Партнёры:&nbsp;</strong>Художественно-графический факультет Витебского государственного университета имени П.М.Машерова</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'>Студия разработки компьютерных игр CarХ Technologies&nbsp;и школа разработки игр Xlab, ООО Экстраверт,&nbsp;Краснодарское региональное отделение общественной организации &laquo;Союз дизайнеров России&raquo;, Технопарк КубГУ, Точка кипения &nbsp;КубГУ,
            ООО &laquo;Рекламный дом Кубани&raquo;, информационный портал cityposter.ru, газета &ldquo;Кубанские новости&raquo;</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'>&nbsp; &nbsp;&nbsp;</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;'><strong>Место проведения:</strong> Россия, Краснодар, Ставропольская, 149</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;'>Кубанский государственный университет, корпус L, центральный вход &nbsp;</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;'><strong>Срок проведения выставки-конкурса:&nbsp;</strong>с 3 апреля &nbsp;по 31 мая 2023</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin-top:15.0pt;margin-bottom:15.0pt;text-align:justify;background:white;'><span style="color:black;background:white;">СИНТЕЗ ИСКУССТВА И НАУКИ.&nbsp;</span><strong><span style="color:black;background:white;">Science</span><span style="color:black;background:white;">&nbsp;</span></strong><strong><span style="color:black;background:white;">Art</span></strong>
            <span style="color:black;background:white;">&nbsp;- это направление современного искусства, находящиеся на стыке художественного, научного, творческого и технологического. Междисциплинарные произведения имеют под собой исследовательскую базу, опирающуюся на достижения учёных, но с обращением
                к эмоциям и зрительным образам. Это позволяет не только осмыслить, но и прочувствовать создаваемое произведение. &nbsp;</span>
        </p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Цель проекта:&nbsp;</strong>выявление и реализация потенциала творческого междисциплинарного взаимодействия и его отражение в образах художественных произведений, выполненных в различных техниках и материалах. Развитие международных научных
            и творческих связей в области синтеза науки, искусства и технологий.</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'>&nbsp;</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;vertical-align:baseline;'><strong><span style="color:black;background:white;">Задачи проекта:</span></strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;vertical-align:baseline;'><span style="color:black;background:white;">- внесение в технологический образ будущего (нано-, био-, инфо- и когнитотехнологий) пятого элемента &ndash; искусства &nbsp;&ndash; &nbsp;как необходимого условия технологической конвергенции и благоприятного эмоционально-чувственного отношения к результатам &nbsp;научных &nbsp;достижений;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;vertical-align:baseline;'><span style="color:black;background:white;">- выстраивание партнерских отношений между участниками научно-образовательных направлений, популяризация, информирование широкой &nbsp;общественности &nbsp;о научных &nbsp; достижениях;&nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;vertical-align:baseline;'><span style="color:black;background:white;">- апробация новых технологий в изобразительном искусстве в рамках инновационного &nbsp;развития &nbsp; художественного &nbsp;образования;&nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;vertical-align:baseline;'><span style="color:black;background:white;">- создание оригинальной выставочной экспозиции в рамках научно-исследовательской и культурно-просветительской деятельности по результатам творческого взаимодействия.</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;vertical-align:baseline;'><span style="color:black;background:white;">&nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><strong><span style="color:black;">Регламент проекта</span></strong><span style="color:black;">:</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><span style="color:black;">- даты проведения арт-проекта с 3 апреля по 31 мая 2023 года;&nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><span style="color:black;">- приём заявок на участие с 10 апреля по 3 мая 2023 года;&nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><span style="color:black;">- работа экспертов с 3 мая по 13 мая 2023 года;&nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:6.0pt;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;margin-top:0cm;margin-bottom:0cm;text-align:justify;text-indent:-6.0pt;background:white;'><span style="color:black;">- открытие итоговой выставки и награждение победителей 18 мая 2023 года в 11.00; &nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:6.0pt;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;margin-top:0cm;margin-bottom:0cm;text-align:justify;text-indent:-6.0pt;background:white;'><span style="color:black;">- участие в выставке &ndash; бесплатно.</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'>&nbsp;</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><strong><span style="color:black;">Участники проекты:</span></strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><strong><span style="color:black;">-&nbsp;</span></strong><span style="color:black;">студенты и сотрудники художественно-графического факультета;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><span style="color:black;">- студенты и сотрудники факультета факультета компьютерных технологий и прикладной математики;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><span style="color:black;">- студенты и сотрудники факультета журналистики;</span></p>
        <p style='margin-right:0cm;margin-left:6.0pt;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;margin-top:0cm;margin-bottom:0cm;text-align:justify;text-indent:-6.0pt;background:white;'><span style="color:black;">- учащиеся детских художественных школ и художественных отделений школ искусств г.Краснодара; &nbsp;&nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><span style="color:black;">- студенты и сотрудники художественно-графического факультета Витебского государственного университета имени П.М.Машерова &nbsp;(Белорусь, Витебск);&nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><span style="color:black;">- студенты и сотрудники колледжа изобразительных искусств университета Бейхуа (Цзилинь, Китай); &nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><span style="color:black;">- студенты и сотрудники факультета искусств университета г.Ниш (Ниш, Сербия);</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><span style="color:black;">- профессиональные художники и&nbsp;</span><span style="color:black;">digital</span><span style="color:black;">&nbsp;</span><span style="color:black;">дизайнеры.&nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'>&nbsp;</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><strong><span style="color:#222222;">Технические требования к конкурсным работам:&nbsp;</span></strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'><span style="color:#222222;">На сайте &laquo;Загрузить файл&raquo; JPEG, размер от 2000 пикселей по меньшей стороне, разрешение от 72 dpi, максимальный вес каждого файла должен быть не меньше 500 кб и не больше 5 Мб.&nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;background:white;'>&nbsp;</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Возрастные категории:</strong> <strong>&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Детский тур &ndash;&nbsp;</strong>участники <strong>Поколение&nbsp;</strong><strong>A&nbsp;</strong>(с 2011)</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Студенческий тур - Поколение&nbsp;</strong><strong>Z</strong> (c 2000- 2015), <strong>Миллениалы (</strong><strong>Y)</strong> (1984-2000 г.р)</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Профессиональный тур</strong> <strong>&ndash;</strong> <strong>Поколение Х</strong> (1967-1984 г.р)</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'>&nbsp;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Программа проведения&nbsp;</strong><strong>*** Международной научно-исследовательской выставки-конкурса &nbsp;ИСКУССТВО И НАУКА: КОСМОС &nbsp;&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;text-indent:35.4pt;'>&nbsp;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;text-indent:35.4pt;'><strong><span style="background:yellow;">7 апреля в 14.00&nbsp;</span>&nbsp; &ndash; экскурсия и посещение участниками арт-проекта мастерских художественно-графического факультета /&nbsp;</strong>Краснодар, Ставропольская, 149, Кубанский государственный
            университет, Художественно-графический факультет<strong>&nbsp;&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;text-indent:35.4pt;'><strong>&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;text-indent:35.4pt;'><strong><span style="background:yellow;">18 апреля в 14.00&nbsp;</span>&nbsp; &ndash; экскурсия и посещение участниками арт-проекта факультета компьютерных технологий и прикладной математики КубГУ</strong> <strong>/&nbsp;</strong>Краснодар, Ставропольская,
            149, Кубанский государственный университет / Лаборатория робототехники <strong>&nbsp;&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;text-indent:35.4pt;'><strong>&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;text-indent:35.4pt;'><strong><span style="background:yellow;">21 апреля в 11.00</span>&nbsp; &nbsp;&ndash;&nbsp;</strong>защита проектов &nbsp;&laquo;IT&nbsp;технологии в искусстве&raquo; в Точке кипения КубГУ / &nbsp; Краснодар, Димитрова, 157</p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;text-indent:35.4pt;'><strong><span style="background:yellow;">24 апреля в 18.00</span>&nbsp; &nbsp;- экскурсия и посещение участниками арт-проекта обсерватории Кубанского государственно университета /&nbsp;</strong>Краснодар, Ставропольская, 149, Кубанский государственный
            университет, Обсерватория</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;text-indent:35.4pt;'>&nbsp;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;text-indent:35.4pt;'><strong><span style="background:yellow;">26 апреля в 14.10</span></strong> &ndash; <strong>семинар &quot;Путь в геймдев через Pet-проекты&quot; студии разработки игр CarX Technologies и школы разработки игр XLab</strong> / КубГУ, Ставропольская,
            149, Литер А ауд.424 &nbsp;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;text-indent:35.4pt;'>&nbsp;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;text-indent:35.4pt;'><strong><span style="background:yellow;">18 мая в 11.00</span>&nbsp; &nbsp;-</strong> <strong>Награждение победителей выставки в КубГУ</strong> / КубГУ, центральный вход, 1 эт. Литер L)<strong>&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><span style="font-size:19px;">&nbsp;</span></p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Жюри выставки-конкурса:&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Шарафан М.В.&nbsp;</strong>Проректор по научной работе и инновациям КубГУ</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Фоменко М.А.</strong> Начальник управления информационными технологиями КубГУ</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Коробко Ю.В.</strong> декан художественно-графического факультета КубГУ</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Соколова Е.</strong>О. декан художественно-графического факультета Витебского государственного университета имени П.М.Машерова</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Морозкина Е.А.</strong> - председатель орг комитета выставки-конкурса, зав.каф ДПИ и дизайна ХГФ КубГУ</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Денисенко В.И</strong>. профессор каф живописи, зам декана по науке ХГФ КубГУ</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Иванов А.Л.&nbsp;</strong>заведующий астрофизической лабораторией оптической лабораторией КубГУ &nbsp;&nbsp;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Копонева О.В.&nbsp;</strong>директор Технопарка КубГУ &nbsp;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Волкова Т.А.&nbsp;</strong>Программный директор &laquo;Точка кипения КубГУ&raquo;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Коваленко А.В.</strong> зав.каф анализа данных и искусственного интеллекта факультета компьютерных технологий и прикладной математики КубГУ</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Лучинский Ю.В.</strong> зав.каф истории и правового регулирования массовых коммуникаций КубГУ</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Литвинский К.О.&nbsp;</strong>зав.каф экономики управления инновационными системами КубГУ</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Зимина О.А.</strong> Председатель Краснодарского регионального отделения &nbsp;общественной организации &laquo;Союз дизайнеров России&raquo;, и.о. декана факультета архитектуры и дизайна, зав. каф &laquo;Дизайн одежды&raquo; ФАД КубГУ;
            &nbsp;&nbsp;
        </p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Говорова Г.Н.</strong> директор Департамента по международным связям;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Ротай Е.М.</strong> зам директора Департамента по международным связям</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Мальцева Л.В.</strong> профессор каф ДПИ и дизайна КубГУ</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Белая Т.В.</strong> доцент каф ДПИ и дизайна ХГФ КубГУ, зам декана по учебной работе ХГФ</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Прокопова А.С.</strong> ст.преподаватель &nbsp;каф ДПИ и дизайна ХГФ КубГУ</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Полонникова А.А.</strong> преподаватель каф ДПИ и дизайна ХГФ КубГУ</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Присяжнюк В.С.</strong> директор детской художественной школы им В.А.Филиппова</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Шведчиков Н.Ю.</strong> генеральный директор ООО Экстраверт</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Золотарёв С.С.&nbsp;</strong>Генеральный директор ООО<strong>&nbsp;</strong>&laquo;М-АРТ&raquo;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Зыкова Е.В.&nbsp;</strong>Управляющий партнёр &laquo;ARTEЛЬ&nbsp;DIGITAL&raquo;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Маталаев Ю.А. &nbsp;</strong>директор ООО &laquo;Рекламный Дом Кубани&raquo;<strong>&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Симоненков О.Н.&nbsp;</strong>графический дизайнер, председатель правления общественной организации &laquo;Смоленское региональное отделение Союза дизайнеров России&raquo;, начальник отдела городского дизайна управления архитектуры и градостроительства
            Администрации города Смоленска</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>Корнев А. Н.</strong>&nbsp; бренд-дизайнер, председатель правления общественной организации &laquo;Владимирское региональное отделение Союза дизайнеров России&raquo;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><strong>&nbsp;</strong></p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'>&nbsp;</p>
        <p style='margin-right:0cm;margin-left:-1.0cm;font-size:16px;font-family:"Times New Roman",serif;margin:0cm;text-align:justify;'><em>*** По &nbsp; вопросам &nbsp;проведения&nbsp;</em><em>III Международной научно-исследовательской выставки&nbsp;</em><em>ScienceART:&nbsp;</em><em>Space&nbsp; 8 9** 275 8888 Морозкина Елена Анатольевна&nbsp;</em><a href="mailto:morozkinaelena@mai.ru"><em>morozkinaelena@</em><em>mai.</em><em>ru</em></a><em>&nbsp;</em></p>
    </div>
    <div style="clear:both;"><br></div>
</div>
""";